# Generated by Django 3.2.6 on 2021-08-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='package',
            name='highlighted_package',
            field=models.TextField(default=''),
        ),
    ]
