# Generated by Django 3.2.6 on 2021-08-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_api', '0005_alter_wishlistitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['price']},
        ),
    ]
